### ISSUE TITLE
Fix Github Workflow action to deploy Github Pages 

### ISSUE THREAD

**Issue by orhantugrul** [AndrewLester/blog#15]

**Comment by orhantugrul** [comment]
So sorry for that :/. Im trying to deploy my home page to Pages. And this issue was for me. So you can delete this.

 Have a nice day!

**Comment by AndrewLester** [comment]
No worries! I hope you got it all working!

**Comment by orhantugrul** [comment]
With the help of your repository, I was able to find a solution to my problem and everything seems to be on track. Thank you again!
